apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend-service
  labels:
    app: frontend
    release: {{ .Release.Name }}
spec:
  type: LoadBalancer
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: 3000
    protocol: TCP
  selector:
    app: frontend
    release: {{ .Release.Name }}